version: "3"

services:
    ######## APP ########
    limas:
        build:
            context: ..
            dockerfile: .docker/Dockerfile
            target: local
        command: "/usr/local/bin/start"
        environment:
            - CONTAINER_ROLE=APP
        volumes:
            - ../:/var/www/app:cached
        ports:
            - 8017:8080
            - 8000:8000

    ######## MYSQL ########
    limas-postgres:
        image: postgres:14.3
        environment:
            - POSTGRES_DB=limasdb
            - POSTGRES_USER=limas
            - POSTGRES_PASSWORD=limas
        volumes:
            - ~/.docker-storage/limas/postgres:/var/lib/postgresql/data
        ports:
            - 5418:5432

    ######## REDIS ########
    limas-redis:
        image: redis:7.0.12
        volumes:
            - ~/.docker-storage/limas/redis:/data
        ports:
            - 6317:6379
